# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_server.proto\"/\n\x0eTerrainRequest\x12\x0f\n\x07surface\x18\x01 \x01(\x01\x12\x0c\n\x04taux\x18\x02 \x01(\x01\"\x1f\n\x0fTerrainResponse\x12\x0c\n\x04prix\x18\x03 \x01(\x01\x32@\n\nServertest\x12\x32\n\rTerrainCalcul\x12\x0f.TerrainRequest\x1a\x10.TerrainResponseB\x18\n\x16org.example.grpc_stubsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026org.example.grpc_stubs'
  _globals['_TERRAINREQUEST']._serialized_start=21
  _globals['_TERRAINREQUEST']._serialized_end=68
  _globals['_TERRAINRESPONSE']._serialized_start=70
  _globals['_TERRAINRESPONSE']._serialized_end=101
  _globals['_SERVERTEST']._serialized_start=103
  _globals['_SERVERTEST']._serialized_end=167
# @@protoc_insertion_point(module_scope)
